.TH GLX 6 "14 September 2025" "0.0.0.1"
.SH NAME
glx \- utilities to manage galaxis communities
.SH SYNOPSIS
.SY glx
.OP \-\-help
.OP \-\-version
.YS
.SH DESCRIPTION
.B glx
explores and manages galaxis communities
.SH OPTIONS
.TP
.BR \-\-help
Print a help message and exit.
.TP
.BR \-\-version
Display version information.
.SH EXIT STATUS
.B glx
always exits with status 0.
.SH COPYRIGHT
Copyright (c) 2025 Andras Kristof. This program is distributed under the MIT
license. See the file
.I LICENSE
distributed with this program for details.
